apiVersion: v1
kind: Service
metadata:
  name: event-management-service
spec:
  selector:
    app: event-management
  ports:
    - protocol: TCP
      port: 80           # External port
      targetPort: 5000   # Flask internal port
      nodePort: 30007    # You can choose any port between 30000–32767
  type: NodePort
